import { uploadThingFileRouter } from "@/app/api/uploadthing/core"
import { ClerkProvider } from "@clerk/nextjs"
import { dark as darkTheme } from "@clerk/themes"
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin"
import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import type { FC, ReactNode } from "react"
import { extractRouterConfig } from "uploadthing/server"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

type Props = Readonly<{
  children: ReactNode;
}>

const RootLayout: FC<Props> = ({ children }) => {
  return (
    <ClerkProvider appearance={{
      baseTheme: darkTheme,
    }}>
      <html lang="en" className="">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <NextSSRPlugin routerConfig={extractRouterConfig(uploadThingFileRouter)}/>
      {children}
      </body>
      </html>
    </ClerkProvider>
  )
}

export default RootLayout
